name: CD Pipeline

on: workflow_dispatch

jobs:

  deploy:

    runs-on: ubuntu-latest
    env:
      EC2_HOST: ec2-user@13.233.107.255
    steps:
    - name: set permission to private key and install docker
      run: |
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    - name: install docker and enable the docker service
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_HOST 'sudo amazon-linux-extras install docker -y'
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_HOST 'sudo systemctl reload docker'
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_HOST 'sudo systemctl enable docker'
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_HOST 'sudo docker pull 07shree/cicd-pipeline:latest'
    - name: Delete Old docker container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_HOST 'sudo docker rm -f cicd-pipeline-container || true'
      
    - name: Run Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_HOST 'sudo docker run -d -p 8080:8080 --name cicd-pipeline-container 07shree/cicd-pipeline'
